[env]
TERM = "xterm-256color"

[shell]
# Shell program - left empty for default shell

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
